open database db2024;
select address, gpa, l2_score, age from dbcourse ;
select age, id, gpa, address, name, l2_score from dbcourse limit 853;
select l2_score from dbcourse limit 57;
select * from dbcourse ;
select gpa, age, l2_score, name from dbcourse ;
select gpa, name, address, l2_score, l1_score from dbcourse ;
select l2_score from dbcourse ;
select l2_score, l1_score, address, age, name from dbcourse ;
select l2_score, name, age, gpa, l1_score from dbcourse ;
select l2_score, id, name, gpa, age from dbcourse ;
select address, l1_score, id, name, gpa from dbcourse ;
select name, gpa, age, address, id, l1_score from dbcourse ;
select gpa, name, id from dbcourse limit 723;
select address, l1_score, age, gpa from dbcourse ;
select l1_score, gpa, address, id from dbcourse ;
select l2_score, address from dbcourse limit 1159;
select l1_score, l2_score, address, gpa, id from dbcourse ;
select id, gpa from dbcourse limit 502;
select id, l1_score, age from dbcourse ;
select gpa, address, id, name, l1_score from dbcourse limit 856;
exit;